name = "cheshiyi"
main = "src/index.js"
compatibility_date = "2024-05-01"

[[d1_databases]]
binding = "cheshiyi"
database_name = "cheshiyi"
database_id = "1697554d-568c-4c8c-9d21-2615f0805329"

[vars]
WEBHOOK_PATH = "/telegram-webhook"
